### ISSUE TITLE
Link para o Monitor não está funcionando

### ISSUE THREAD

**Issue by vkruoso** [nfe/ws-monitor#1]
O link do README para http://monitor.nfe.io não está funcional.

**Comment by sandsu** [comment]
pretendem corrigir isso?

**Comment by bruno-alencar** [comment]
@vkruoso @sandsu 
Hoje criamos uma aplicação para monitoramento das prefeituras no seguinte link:
https://caiu.la/prefeituras.
Caso tenham interesse em ajudar no código, podemos verificar a disponibilização.

**Comment by sandsu** [comment]
ficou muito legal @bruno-alencar, não poderia pensar em algo melhor.
se a gente puder contribuir seria ótimo.

**Comment by gblmarquez** [comment]
@sandsu vamos marcar um call para conversamos sobre isso? O que acha de marcar o melhor horário para você direto na minha agenda http://gabriel.nfe.io, assim já explicamos o que  fizemos o um pouco do roadmap além disso já abrimos os fontes.

**Comment by gblmarquez** [comment]
@vkruoso caso queira participar também será muito bem-vindo :)
